#! /bin/sh
mkdir -p ./builder
curl -o ./rack_builder_spec.rb https://raw.github.com/rack/rack/master/test/spec_builder.rb
curl -o ./builder/anything.rb https://raw.github.com/rack/rack/master/test/builder/anything.rb
curl -o ./builder/comment.ru https://raw.github.com/rack/rack/master/test/builder/comment.ru
curl -o ./builder/end.ru https://raw.github.com/rack/rack/master/test/builder/end.ru
curl -o ./builder/options.ru https://raw.github.com/rack/rack/master/test/builder/options.ru
